"""KDA typed-IR vertical slice."""

from .fixtures import B300, cake_bt16_prepare_chain, official_flashkda, value_sliced_v16
from .cutlass_ts import (
    LeaderArrivalSplitConsumerPlan,
    cutlass_task_scheduling_plan,
    leader_arrival_split_consumer_plans,
    split_phase_lowering_analysis,
)
from .cutlass_runtime import (
    CutlassTsCodegenCapabilities,
    custom_work_codegen_diagnostics,
    instantiate_pipeline_configs,
    pipeline_runtime_specs,
)
from .kda_first_edge import (
    CompletionDominanceProof,
    KdaQkFirstEdge,
    qk_first_edge_schedule,
    qk_raw_runtime_plan,
    recover_qk_first_edge,
)
from .model import ArrivalMode, CompletionJoin, SplitPhaseFanout
from .evolve import EvolutionResult, FailureLedger, Proposal, evolve
from .multi_agent import (
    ActivationDecision,
    ActivationEvidence,
    ActivationStatus,
    AgentContribution,
    AgentRole,
    CoordinatedCandidate,
    CoordinationResult,
    activation_decision,
    coordinate_contributions,
)
from .lower import lowering_plan
from .mutate import (
    break_token_order,
    retile_value,
    set_pipeline_stages,
    set_prepare_chunks_per_cta,
)
from .semantic_delta import (
    BlackwellScheduleDelta,
    DispatchTopology,
    WorkloadSignature,
    corpus_from_source_dir,
    deduplicate_semantics,
    is_workload_compatible,
    parse_blackwell_schedule_delta,
    verify_blackwell_schedule_delta,
)
from .verify import Diagnostic, VerificationError, require_valid, verify
from .runtime_profile import (
    PrepareGridGeometry,
    ResidentWaveRecommendation,
    RuntimeWorkloadProfile,
    prepare_grid_geometry,
    recommend_one_resident_wave_cpc,
    runtime_profile_receipt,
)
from .autonomous_agent import (
    AutonomousRuntimeProfileAgent,
    Conclusion,
    ConclusionsMemory,
    LoopResult,
    MeasurementOracle,
    QualificationResult,
    RoundResult,
    ScreenResult,
    canonical_candidate_id,
)
from .ablation import (
    AblationArm,
    AblationAudit,
    ArmReceipt,
    EqualBudgetContract,
    audit_equal_budget_ablation,
    multi_agent_advantage,
)
from .runtime_policy import (
    PolicyGuardResult,
    PolicyResolution,
    PrepareKernelReceipt,
    ResidentGridPolicyV1,
    RuntimeCallContract,
    RuntimePolicyStatus,
    canonical_sha256,
    qualified_h12_call_contract,
    resolve_resident_grid_policy,
)
from .mma_migration import (
    KernelMeasurement,
    MigrationAction,
    MmaMigrationAssessment,
    MmaMigrationProfile,
    MmaOptimizationProposal,
    PhysicalFinding,
    assess_mma_migration,
)
from .mma_evidence import build_mma_profile_from_evidence, profile_to_dict

__all__ = [
    "B300",
    "AblationArm",
    "AblationAudit",
    "AutonomousRuntimeProfileAgent",
    "ArrivalMode",
    "ArmReceipt",
    "ActivationDecision",
    "ActivationEvidence",
    "ActivationStatus",
    "AgentContribution",
    "AgentRole",
    "BlackwellScheduleDelta",
    "CutlassTsCodegenCapabilities",
    "CompletionJoin",
    "Conclusion",
    "ConclusionsMemory",
    "CompletionDominanceProof",
    "CoordinatedCandidate",
    "CoordinationResult",
    "Diagnostic",
    "DispatchTopology",
    "EvolutionResult",
    "EqualBudgetContract",
    "FailureLedger",
    "KdaQkFirstEdge",
    "LeaderArrivalSplitConsumerPlan",
    "LoopResult",
    "MeasurementOracle",
    "KernelMeasurement",
    "MigrationAction",
    "MmaMigrationAssessment",
    "MmaMigrationProfile",
    "MmaOptimizationProposal",
    "Proposal",
    "QualificationResult",
    "PrepareGridGeometry",
    "PrepareKernelReceipt",
    "PolicyGuardResult",
    "PolicyResolution",
    "PhysicalFinding",
    "ResidentWaveRecommendation",
    "ResidentGridPolicyV1",
    "RuntimeCallContract",
    "RuntimePolicyStatus",
    "RuntimeWorkloadProfile",
    "RoundResult",
    "ScreenResult",
    "SplitPhaseFanout",
    "VerificationError",
    "WorkloadSignature",
    "break_token_order",
    "activation_decision",
    "assess_mma_migration",
    "build_mma_profile_from_evidence",
    "audit_equal_budget_ablation",
    "cake_bt16_prepare_chain",
    "canonical_candidate_id",
    "canonical_sha256",
    "cutlass_task_scheduling_plan",
    "custom_work_codegen_diagnostics",
    "corpus_from_source_dir",
    "coordinate_contributions",
    "deduplicate_semantics",
    "instantiate_pipeline_configs",
    "is_workload_compatible",
    "pipeline_runtime_specs",
    "prepare_grid_geometry",
    "profile_to_dict",
    "recommend_one_resident_wave_cpc",
    "parse_blackwell_schedule_delta",
    "qk_raw_runtime_plan",
    "qk_first_edge_schedule",
    "recover_qk_first_edge",
    "qualified_h12_call_contract",
    "resolve_resident_grid_policy",
    "split_phase_lowering_analysis",
    "evolve",
    "lowering_plan",
    "multi_agent_advantage",
    "leader_arrival_split_consumer_plans",
    "official_flashkda",
    "require_valid",
    "retile_value",
    "runtime_profile_receipt",
    "set_pipeline_stages",
    "set_prepare_chunks_per_cta",
    "value_sliced_v16",
    "verify",
    "verify_blackwell_schedule_delta",
]
